Repository iterative/shtab, pull requests merged in 2022-10, with the labels that each got.

#96 Fix typos
  shtab/__init__.py
  shtab/main.py
  tests/test_shtab.py
Labels: documentation, hacktoberfest, technical-debt

#110 Fix colons in subcommands
  shtab/__init__.py
  tests/test_shtab.py
Labels: enhancement, shell-bash, shell-zsh, hacktoberfest

#108 Fix subcommands with hyphens (and periods, spaces, etc) in zsh
  shtab/__init__.py
Labels: p0-critical, shell-zsh, external-request

#106 Fix subcommand/choices completion in bash
  shtab/__init__.py
Labels: p0-critical, enhancement, shell-bash, external-request
