Repository iterative/shtab, pull requests merged in 2023-07, with the labels that each got.

#141 minor docs updates
  README.rst
  docs/index.md
Labels: documentation

#140 expand help `'%(variables)'`
  shtab/__init__.py
Labels: enhancement, shell-zsh, good-first-issue, external-request

#143 bash `nounset` mode fixes
  shtab/__init__.py
  tests/test_shtab.py
Labels: shell-bash

#144 Match bash current word exactly instead of as regex
  shtab/__init__.py
Labels: enhancement, shell-bash, external-request

#145 bash variable leak fixes
  shtab/__init__.py
Labels: shell-bash, technical-debt, external-request

#148 Type hinting
  shtab/__init__.py
Labels: technical-debt, external-request
