Repository iterative/shtab, pull requests merged in 2023-06, with the labels that each got.

#139 misc framework updates
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  docs/requirements.txt
  pyproject.toml
  requirements-dev.txt
  setup.cfg
  setup.py
  shtab/__init__.py
Labels: documentation, testing, p1-important, technical-debt

#112 tcsh: Fix autocompletion for no single-hyphen args
  shtab/__init__.py
Labels: shell-tcsh, good-first-issue, external-request

#137 fix for zsh completion not allowing single-letter stacking
  shtab/__init__.py
Labels: enhancement, shell-zsh
